### ISSUE TITLE
Publish to npm?

### ISSUE THREAD

**Issue by marionebl** [audi/audi-icon#2]
Publishing to npm would speed up installing this as dependency considerably. Probably depends on #1.

**Comment by thomasmichelbach** [comment]
@marionebl thanks for your feedback! we're considering this for the icons as well as the ui kit. As soon as we have officially clarified licensing we'll get back to this!

**Comment by thomasmichelbach** [comment]
@marionebl icons & typefaces have now been published to npm: 

https://www.npmjs.com/package/@audi/audi-icon
https://www.npmjs.com/package/@audi/audi-type
